# Generated by Django 5.2.7 on 2025-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_experience_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="experience_level",
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                help_text="FontAwesome icon class (e.g., 'fas fa-code')", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
